FROM dotnet-20-rhel7:latest
# This image provides a .NET Core 2.0 environment you can use to run your .NET
# applications.

USER 0

# Install Java JDK 8
 RUN yum install java-1.8.0-openjdk-devel

USER 1001
